---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mknsec/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp TWHD.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R TWHD $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH